local ui = UserInterface.new("FullUIExample", "Verified")

ui:addLabel("Hello World")
ui:addLabelApp("GrowLauncher UI", "Verified")
ui:addToggle("Enable Feature", true, "feat_toggle", true)
ui:addToggleButton("Power Button", false, "power_btn")
ui:addButton("Click Me", "btn_click")

local expand = ui:addExpandableToggle("Advanced Settings", false, "adv_toggle", true, true)
    ui:addChildToggle(expand.list_child,"Enable Child", true, "child_toggle")
    ui:addChildSlider(expand.list_child,"Child Slider", 0, 100, 50, 1, false, "child_slider")
    ui:addChildTooltip(expand.list_child,"Tooltip Title", "Support text here", "Verified", true)
    ui:addChildItemPicker(expand.list_child,"Pick Item", "Dirt", "2", "child_item")
    ui:addChildInputInt(expand.list_child,"Child Int", "1", "Label", "Enter number", "Verified", "child_int")
    ui:addChildInputString(expand.list_child,"Child String", "abc", "Label", "Type text", "Home", "child_str")
    ui:addChildButton(expand.list_child,"Child Button", "child_btn")

ui:addSlider("Main Slider", 0, 100, 50, 1, false, "main_slider")
ui:addInputInt("Enter Number", "10", "Label", "Type..", "Verified", "int_alias")
ui:addInputString("Enter Text", "abc", "Label", "Type..", "Verified", "str_alias")
ui:addTooltip("Info Tooltip", "Support text", "Verified", true)
ui:addItemPicker("Choose Item", "Dirt", "2", "picker")
ui:addDivider()
ui:addDisplayList("List Example", "Default", "list_alias")
ui:addTileSelect("Tile Select", "Default", "tile_alias", 5)

local dialog = ui:addDialog("Dialog Title", "Sub text", {})
    ui:addChildToggle(dialog.menu,"Enable Child", true, "child_toggle")
    ui:addChildSlider(dialog.menu,"Child Slider", 0, 100, 50, 1, false, "child_slider")
    ui:addChildTooltip(dialog.menu,"Tooltip Title", "Support text here", "Verified", true)
    ui:addChildItemPicker(dialog.menu,"Pick Item", "Dirt", "2", "child_item")
    ui:addChildInputInt(dialog.menu,"Child Int", "1", "Label", "Enter number", "Verified", "child_int")
    ui:addChildInputString(dialog.menu,"Child String", "abc", "Label", "Type text", "Home", "child_str")
    ui:addChildButton(dialog.menu,"Child Button", "child_btn")

local json = ui:generateJSON()

require("IniEy")
addIntoModule(json,"IniEy")